# Generated by Django 5.0.4 on 2024-05-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='name',
            field=models.TextField(),
        ),
    ]
